version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cb-db?retryWrites=true&w=majority
    restart: unless-stopped