version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    environment:
    #   # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234567
    ports:
      - 27017:27017
    restart: unless-stopped
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://root:1234567@mongodb:27017/cb-db?authSource=admin&retryWrites=true&w=majority
    restart: unless-stopped